navbar_style: navbar-dark
navbar_bgcolor: '#222222'
navbar_position: top
navbar_breakpoint: md
git_sync.edit_theme_link_location: none
dropdown:
  enabled: false
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/mytheme, user/themes/bootstrap4-open-matter, user/themes/bootstrap4]
menu:
  -
    text: Grav
    icon: arrow-circle-right
    url: 'http://getgrav.org/'
    target: _self
chromeless:
  enabled: false
display_of_git_sync_repo_link: page
type_of_git_sync_repo_link: edit
git_sync_edit_note_text: 'Have a suggestion or correction?'
git_sync:
  edit_theme_link_location: none
  edit_theme_link_text: 'Site Theme Files'
h5pembedrootpath: 'https://h5p.org/h5p/embed/'
cc_license:
  enabled: false
  type: ccby
  icon: false
hidehomemenulink: false
displaycustommenus:
  enabled: false
